# Generated by Django 4.2.3 on 2023-07-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bebidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('bebidas', models.ManyToManyField(blank=True, to='Bebidas.bebidas')),
            ],
        ),
    ]
