# Generated by Django 4.2.3 on 2023-08-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('mesa', models.CharField(max_length=100, null=True)),
                ('items', models.ManyToManyField(blank=True, to='items.items')),
            ],
        ),
    ]
