# Generated by Django 4.2.3 on 2023-07-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cocteles', '0001_initial'),
        ('Comidas', '0001_initial'),
        ('Cristaleria', '0001_initial'),
        ('Orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cocteles',
            field=models.ManyToManyField(blank=True, to='Cocteles.cocteles'),
        ),
        migrations.AddField(
            model_name='orden',
            name='comida',
            field=models.ManyToManyField(blank=True, to='Comidas.comidas'),
        ),
        migrations.AddField(
            model_name='orden',
            name='cristaleria',
            field=models.ManyToManyField(blank=True, to='Cristaleria.cristaleria'),
        ),
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='mesa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
